In [92]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [93]:
df = pd.read_csv('/content/netflix_titles.csv')

In [94]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Checking number of rows and columns in the data

In [95]:
df.shape

(8807, 12)

In [96]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [97]:
x = df.groupby(df['rating']).size().reset_index(name = 'counts')
x

      rating  counts
0     66 min       1
1     74 min       1
2     84 min       1
3          G      41
4      NC-17       3
5         NR      80
6         PG     287
7      PG-13     490
8          R     799
9      TV-14    2160
10      TV-G     220
11     TV-MA    3207
12     TV-PG     863
13      TV-Y     307
14     TV-Y7     334
15  TV-Y7-FV       6
16        UR       3

In [98]:
import plotly.express as px #used for data visualization
from textblob import TextBlob #used for sentiment analysis

In [99]:
pieChart = px.pie(x ,values = 'counts' , names = 'rating' ,title = 'Distribution of Content Ratings on Netflix')
pieChart.show()

In [100]:
df['director'] = df['director'].fillna('Director not specified')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Director not specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Director not specified,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Director not specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [101]:
df['director'].isnull().sum()

np.int64(0)

Therefore we can see that there are no missing values in director column

In [102]:
director_df = df[['director']].copy()
director_df['director'] = director_df['director'].str.split(',')
director_df = director_df.explode('director')
director_df['director'] = director_df['director'].str.strip()

In [103]:
print(director_df) # you can see the type ,its a dataframe

                    director
0            Kirsten Johnson
1     Director not specified
2            Julien Leclercq
3     Director not specified
4     Director not specified
...                      ...
8802           David Fincher
8803  Director not specified
8804         Ruben Fleischer
8805            Peter Hewitt
8806             Mozez Singh

[9612 rows x 1 columns]

In [104]:
director = director_df.groupby(['director']).size().reset_index(name = 'Total Counts')
print(director)

                 director  Total Counts
0             A. L. Vijay             2
1            A. Raajdheep             1
2               A. Salaam             1
3         A.R. Murugadoss             2
4         Aadish Keluskar             1
...                   ...           ...
4989           Éric Warin             1
4990     Ísold Uggadóttir             1
4991  Óskar Thór Axelsson             1
4992     Ömer Faruk Sorak             3
4993         Şenol Sönmez             2

[4994 rows x 2 columns]

In [105]:
# Cleaning the data
director = director[director.director != 'Director not specified']
print(director)

                 director  Total Counts
0             A. L. Vijay             2
1            A. Raajdheep             1
2               A. Salaam             1
3         A.R. Murugadoss             2
4         Aadish Keluskar             1
...                   ...           ...
4989           Éric Warin             1
4990     Ísold Uggadóttir             1
4991  Óskar Thór Axelsson             1
4992     Ömer Faruk Sorak             3
4993         Şenol Sönmez             2

[4993 rows x 2 columns]

In [106]:
# to find the top 5 director
director = director.sort_values(by = ['Total Counts'] , ascending = False)
print(director)

             director  Total Counts
3750    Rajiv Chilaka            22
1907        Jan Suter            21
3801      Raúl Campos            19
2867     Marcus Raboy            16
4458      Suhas Kadav            16
...               ...           ...
8         Aaron Burns             1
7          Aanand Rai             1
6          Aamir Khan             1
5        Aamir Bashir             1
4     Aadish Keluskar             1

[4993 rows x 2 columns]

In [107]:
top5Director = director.head()
print(top5Director)

           director  Total Counts
3750  Rajiv Chilaka            22
1907      Jan Suter            21
3801    Raúl Campos            19
2867   Marcus Raboy            16
4458    Suhas Kadav            16

In [108]:
top5Director = top5Director.sort_values(by = ['Total Counts'] , ascending = True)

In [109]:
barChart = px.bar(top5Director , x = 'Total Counts' ,y = 'director' , title = 'Top 5 Directors on Netflix')
barChart.show()

In [110]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [111]:
df['cast'].head()

0                                                  NaN
1    Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
2    Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
3                                                  NaN
4    Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...
Name: cast, dtype: object

In [112]:
df['cast'] = df['cast'].fillna('Cast not specified')
df.cast

0                                      Cast not specified
1       Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
2       Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
3                                      Cast not specified
4       Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...
                              ...
8802    Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...
8803                                   Cast not specified
8804    Jesse Eisenberg, Woody Harrelson, Emma Stone, ...
8805    Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...
8806    Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...
Name: cast, Length: 8807, dtype: object

In [113]:
cast_df = pd.DataFrame()
cast_df = df['cast'].str.split(',',expand = True).stack()
cast_df = cast_df.to_frame()
cast_df.columns = ['Actor']
actors = cast_df.groupby(['Actor']).size().reset_index(name = 'Total count')
actors = actors[actors.Actor != 'Cast not specified']
actors.sort_values(by = ['Total count'] , ascending = False, inplace = True)
top5Actors = actors.head().copy()
top5Actors.sort_values(by = ['Total count'], ascending = True, inplace = True)
top5Actors = top5Actors.reset_index(drop=True)
top5Actors

               Actor  Total count
0            Om Puri           27
1      Julie Tejwani           28
2   Takahiro Sakurai           30
3       Rupa Bhimani           31
4        Anupam Kher           39

In [114]:
barChart2 = px.bar(top5Actors , x = 'Total count' , y = 'Actor' ,title = 'Top 5 actors on netflix')
barChart2.show()

Analyzing the content produced on netfix based on the years

In [115]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [116]:
df1 = df[['type' , 'release_year']]
df1 = df1.rename(columns = {"release_year" : "Release Year" , "type" : "Type"})

In [117]:
df2 = df1.groupby(['Release Year','Type']).size().reset_index(name = 'Total Counts')

In [118]:
df2

     Release Year     Type  Total Counts
0            1925  TV Show             1
1            1942    Movie             2
2            1943    Movie             3
3            1944    Movie             3
4            1945    Movie             3
..            ...      ...           ...
114          2019  TV Show           397
115          2020    Movie           517
116          2020  TV Show           436
117          2021    Movie           277
118          2021  TV Show           315

[119 rows x 3 columns]

In [119]:
df2 = df2[df2['Release Year'] >= 2000]
graph = px.line(df2 , x = 'Release Year' , y = 'Total Counts' , color = 'Type' ,title = 'trends')
graph.show()

Sentiment analysis of netflix content

In [120]:
df.columns
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Cast not specified,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Director not specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Director not specified,Cast not specified,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Director not specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [121]:
df3 = df[['release_year','description']]
df3 = df3.rename(columns = {"release_year" : "Release Year" , "description" : "Description"})
for index, row in df3.iterrows():
  d=row['Description']
  testimonial = TextBlob(d)
  p = testimonial.sentiment.polarity
  if p==0:
    sent = 'Neutral'
  elif p>0:
    sent = 'Positive'
  else:
    sent = 'Negative'
  df3.loc[[index, 2], 'Sentiment']=sent

df3 = df3.groupby(['Release Year', 'Sentiment']).size().reset_index(name = 'Total Count')

df3 = df3[df3['Release Year']>2005]
barGraph = px.bar(df3, x="Release Year", y="Total Count", color = "Sentiment", title = "Sentiment Analysis of Content on Netflix")
barGraph.show()